'use client';
import { useEffect, useState } from 'react';
import Nav from '@/components/Nav';

type Q={id:string;section:'A'|'B';topic:string;difficulty:'Easy'|'Medium'|'Hard';question:string;options:string[];correct_answer:number;explanation:string;source_type:string;source_label:string};
const empty:Q={id:'',section:'A',topic:'',difficulty:'Medium',question:'',options:['','','',''],correct_answer:0,explanation:'',source_type:'Original',source_label:'Original practice'};
export default function AdminQuestions(){
 const [items,setItems]=useState<Q[]>([]); const [flags,setFlags]=useState<any[]>([]); const [csvBusy,setCsvBusy]=useState(false); const [form,setForm]=useState<Q>(empty); const [editing,setEditing]=useState(false); const [q,setQ]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch(`/api/admin/questions?q=${encodeURIComponent(q)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load');setItems(d.questions||[])};
 async function loadFlags(){const r=await fetch('/api/admin/flags');const d=await r.json();if(r.ok)setFlags(d.flags||[])}
 useEffect(()=>{load().catch(e=>setError(e.message));loadFlags().catch(()=>{})},[]);
 const save=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/questions',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed');setForm(empty);setEditing(false);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 
 const importCSV=async(file:File)=>{setCsvBusy(true);setError('');try{const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('CSV is empty');const parse=(line:string)=>{const out:string[]=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='\"'&&line[i+1]==='\"'){cur+='\"';i++;continue}if(c==='\"')quote=!quote;else if(c===','&&!quote){out.push(cur);cur=''}else cur+=c}out.push(cur);return out};const headers=parse(lines[0]).map(x=>x.trim());const rows=lines.slice(1).map(line=>{const vals=parse(line);const o:any={};headers.forEach((h,i)=>o[h]=vals[i]??'');o.options=[o.option_a,o.option_b,o.option_c,o.option_d];o.correct_answer=/^[A-Da-d]$/.test(o.correct_answer)?o.correct_answer.toUpperCase().charCodeAt(0)-65:Number(o.correct_answer);return o});const r=await fetch('/api/admin/questions/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questions:rows})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Import failed');await load();alert(`Imported ${d.imported} questions`)}catch(e:any){setError(e.message)}finally{setCsvBusy(false)}}
 async function updateFlag(f:any,status:string){const r=await fetch('/api/admin/flags',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:f.id,status,adminNote:f.admin_note||''})});if(r.ok)loadFlags()}

 const remove=async(id:string)=>{if(!confirm(`Delete ${id}?`))return;const r=await fetch(`/api/admin/questions?id=${encodeURIComponent(id)}`,{method:'DELETE'});const d=await r.json();if(!r.ok)setError(d.error||'Delete failed');else load()};
 return <div className="shell"><Nav/><main className="container"><div className="section-title"><div><div className="eyebrow">ADMIN CONSOLE</div><h1>Question Manager</h1><p className="muted">Admin-only CRUD with server authorization and RLS.</p></div><span className="pill">{items.length} loaded</span></div>
 <div className="card"><div className="toolbar"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search id, topic or question"/><button className="btn ghost" onClick={()=>load()}>Search</button><button className="btn primary" onClick={()=>{setForm(empty);setEditing(false)}}>New question</button></div></div>
 {error&&<div className="notice error" style={{marginTop:14}}>{error}</div>}
 <div className="card" style={{marginTop:14}}><div className="section-title" style={{marginTop:0}}><h2>Bulk CSV import</h2><span className="muted">Columns: id,section,topic,difficulty,question,option_a,option_b,option_c,option_d,correct_answer,explanation,source_type,source_label</span></div><input className="input" type="file" accept=".csv,text/csv" disabled={csvBusy} onChange={e=>e.target.files?.[0]&&importCSV(e.target.files[0])}/></div>
 <div className="card" style={{marginTop:14}}><h2>{editing?'Edit question':'Create question'}</h2><div className="grid2"><label>ID<input className="input" value={form.id} disabled={editing} onChange={e=>setForm({...form,id:e.target.value})}/></label><label>Section<select className="input" value={form.section} onChange={e=>setForm({...form,section:e.target.value as 'A'|'B'})}><option>A</option><option>B</option></select></label><label>Topic<input className="input" value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></label><label>Difficulty<select className="input" value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value as Q['difficulty']})}><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><label>Question<textarea className="input" value={form.question} onChange={e=>setForm({...form,question:e.target.value})}/></label><div className="grid2">{form.options.map((x,i)=><label key={i}>Option {String.fromCharCode(65+i)}<input className="input" value={x} onChange={e=>setForm({...form,options:form.options.map((v,n)=>n===i?e.target.value:v)})}/></label>)}</div><div className="grid2"><label>Correct option<select className="input" value={form.correct_answer} onChange={e=>setForm({...form,correct_answer:Number(e.target.value)})}><option value={0}>A</option><option value={1}>B</option><option value={2}>C</option><option value={3}>D</option></select></label><label>Source<input className="input" value={form.source_label} onChange={e=>setForm({...form,source_label:e.target.value})}/></label></div><label>Explanation<textarea className="input" value={form.explanation} onChange={e=>setForm({...form,explanation:e.target.value})}/></label><div className="toolbar"><button className="btn primary" disabled={busy} onClick={save}>{busy?'Saving…':editing?'Update':'Create'}</button>{editing&&<button className="btn ghost" onClick={()=>{setEditing(false);setForm(empty)}}>Cancel</button>}</div></div>
 <div className="card" style={{marginTop:14}}><div className="section-title" style={{marginTop:0}}><div><h2>Content flag queue</h2><p className="muted">Review problematic questions reported by students.</p></div><span className="pill">{flags.filter(f=>f.status==='open').length} open</span></div><div className="list">{flags.filter(f=>f.status!=='dismissed').slice(0,30).map(f=><div className="row" key={f.id}><div><b>{f.question_id}</b> · {f.reason}<div className="muted">{f.details}</div></div><div className="toolbar"><button className="btn ghost" onClick={()=>updateFlag(f,'reviewing')}>Reviewing</button><button className="btn primary" onClick={()=>updateFlag(f,'resolved')}>Resolve</button><button className="btn ghost" onClick={()=>updateFlag(f,'dismissed')}>Dismiss</button></div></div>)}</div></div>
 <div className="card" style={{marginTop:14,overflowX:'auto'}}><table className="table"><thead><tr><th>ID</th><th>Section</th><th>Topic</th><th>Difficulty</th><th>Question</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.section}</td><td>{x.topic}</td><td>{x.difficulty}</td><td>{x.question}</td><td><div className="toolbar"><button className="btn ghost" onClick={()=>{setForm(x);setEditing(true)}}>Edit</button><button className="btn ghost" onClick={()=>remove(x.id)}>Delete</button></div></td></tr>)}</tbody></table></div>
 </main></div>
}
