'use client';
import { useMemo } from 'react';

type Attempt={id:string;mode:string;score:number;correct_count:number;wrong_count:number;unanswered_count:number;created_at:string};
type Topic={topic:string;correct:number;total:number};

function Heatmap({attempts}:{attempts:Attempt[]}){
 const days=useMemo(()=>{const map=new Map<string,number>();attempts.forEach(a=>{const d=a.created_at.slice(0,10);map.set(d,(map.get(d)||0)+a.correct_count)});const end=new Date();const out: {date:string;count:number}[]=[];for(let i=111;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);const date=d.toISOString().slice(0,10);out.push({date,count:map.get(date)||0});}return out;},[attempts]);
 return <div><div className="heatmap" aria-label="Activity heatmap">{days.map(d=><span key={d.date} title={`${d.date}: ${d.count} correct`} className={`heat-${Math.min(4,Math.ceil(d.count/5))}`}/>)}</div><div className="heat-legend"><span>Less</span><i className="heat-0"/><i className="heat-1"/><i className="heat-2"/><i className="heat-3"/><i className="heat-4"/><span>More</span></div></div>
}
function Radar({topics}:{topics:Topic[]}){
 const vals=topics.slice(0,8); if(!vals.length)return <div className="notice">Complete practice or mock questions to unlock the skill map.</div>;
 return <div className="radar-wrap"><div className="radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="radar-axis a1"/><div className="radar-axis a2"/><div className="radar-axis a3"/><div className="radar-axis a4"/><div className="radar-axis a5"/><div className="radar-axis a6"/><div className="radar-axis a7"/><div className="radar-axis a8"/><div className="radar-fill"/></div><div className="radar-labels">{vals.map((t,i)=><span key={t.topic} style={{['--i' as string]:i}}>{t.topic}</span>)}</div></div>
}
export default function AnalyticsDashboard({attempts,topics}:{attempts:Attempt[];topics:Topic[]}){
 const stats=useMemo(()=>{const total=attempts.reduce((s,a)=>s+a.correct_count+a.wrong_count+a.unanswered_count,0);const correct=attempts.reduce((s,a)=>s+a.correct_count,0);const avg=attempts.length?Math.round(attempts.reduce((s,a)=>s+a.score,0)/attempts.length):0;return {accuracy:total?Math.round(correct/total*100):0,avg,best:attempts.length?Math.max(...attempts.map(a=>a.score)):0};},[attempts]);
 return <div className="grid" style={{gap:16}}><div className="stats"><div className="stat"><span>Attempts</span><b>{attempts.length}</b></div><div className="stat"><span>Average score</span><b>{stats.avg}</b></div><div className="stat"><span>Accuracy</span><b>{stats.accuracy}%</b></div><div className="stat"><span>Best score</span><b>{stats.best}</b></div></div><div className="grid2"><section className="card"><div className="section-title" style={{marginTop:0}}><div><div className="eyebrow">DAILY ACTIVITY</div><h2>Consistency heatmap</h2></div><span className="pill">Last 16 weeks</span></div><Heatmap attempts={attempts}/></section><section className="card"><div className="section-title" style={{marginTop:0}}><div><div className="eyebrow">SKILL MAP</div><h2>Topic proficiency</h2></div></div><Radar topics={topics}/></section></div><section className="card"><div className="section-title" style={{marginTop:0}}><div><div className="eyebrow">TOPIC PERFORMANCE</div><h2>Strengths & weak areas</h2></div></div><div className="topic-bars">{topics.map(t=>{const pct=t.total?Math.round(t.correct/t.total*100):0;return <div className="topic-bar" key={t.topic}><div><span>{t.topic}</span><b>{pct}%</b></div><div className="bar"><span style={{width:`${pct}%`}}/></div></div>})}</div></section><section className="card"><div className="section-title" style={{marginTop:0}}><div><div className="eyebrow">RECENT ACTIVITY</div><h2>Mock history</h2></div></div><div className="list">{attempts.length?attempts.slice(0,10).map(a=><div className="row" key={a.id}><span><b>{a.mode}</b><small className="muted"> · {new Date(a.created_at).toLocaleString()}</small></span><b>{a.score} marks</b></div>):<p className="muted">No attempts yet.</p>}</div></section></div>
}
