import Link from 'next/link';
import Nav from '@/components/Nav';
import {createClient} from '@/lib/supabase/server';
import AnalyticsDashboard from '@/components/AnalyticsDashboard';

export default async function Dashboard(){
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return null;
 const [{count},{data:attempts},{data:activity},{data:achievements},{data:globalAvg}]=await Promise.all([
  s.from('questions').select('*',{count:'exact',head:true}),
  s.from('exam_attempts').select('id,score,correct_count,wrong_count,unanswered_count,created_at,mode').eq('user_id',user.id).order('created_at',{ascending:false}).limit(120),
  s.from('daily_activity').select('activity_date,practice_count,questions_solved,questions_attempted').eq('user_id',user.id).order('activity_date',{ascending:false}).limit(60),
  s.from('user_achievements').select('achievement_key,awarded_at,achievements(name,description,icon)').eq('user_id',user.id).order('awarded_at',{ascending:false}),
  s.rpc('get_global_average')
 ]);
 const ids=(attempts||[]).map(a=>a.id);
 const {data:answers}=ids.length?await s.from('attempt_answers').select('question_id,is_correct,questions!inner(topic)').in('attempt_id',ids):{data:[]};
 const topicMap=new Map<string,{correct:number;total:number}>();(answers||[]).forEach((a:any)=>{const topic=a.questions?.topic||'Unknown';const x=topicMap.get(topic)||{correct:0,total:0};x.total++;if(a.is_correct)x.correct++;topicMap.set(topic,x)});
 const topics=Array.from(topicMap.entries()).map(([topic,v])=>({topic,...v})).sort((a,b)=>(b.correct/b.total)-(a.correct/a.total));
 const latestScore=attempts?.[0]?.score??0; const streakDates=(activity||[]).map(x=>x.activity_date); let streak=0; let cursor=new Date(new Date().toISOString().slice(0,10)+'T00:00:00Z'); for(const date of streakDates){const d=new Date(date+'T00:00:00Z');if(d.getTime()===cursor.getTime()){streak++;cursor.setUTCDate(cursor.getUTCDate()-1)}else break;} const globalAverage=Number(globalAvg||0);
 return <div className="shell"><Nav/><main className="container"><section className="hero"><div className="card"><div className="eyebrow">C-CAT PREPARATION • V5.6/V5.7</div><h1>Train like the real exam.</h1><p className="muted">Solve problems, build streaks, understand weak topics and turn mistakes into revision.</p><div className="toolbar"><Link className="btn primary" href="/mock">Start 2-Hour Mock</Link><Link className="btn ghost" href="/practice">Practice Problems</Link><Link className="btn ghost" href="/revision">Open Revision</Link></div></div><div className="card"><h2>Exam structure</h2><p>Section A — 50 Q • 60 min • 150 marks</p><p>Section B — 50 Q • 60 min • 150 marks</p><p className="notice">+3 correct • −1 wrong • 0 unattempted</p></div></section><div className="stats"><div className="stat"><span>Question bank</span><b>{count??0}</b></div><div className="stat"><span>Mocks completed</span><b>{attempts?.length??0}</b></div><div className="stat"><span>Latest score</span><b>{attempts?.[0]?.score??0}</b></div><div className="stat"><span>Best score</span><b>{attempts?.length?Math.max(...attempts.map(a=>a.score)):0}</b></div></div><div className="stats"><div className="stat"><span>🔥 Daily streak</span><b>{streak} days</b></div><div className="stat"><span>🌍 Global average</span><b>{globalAverage}</b></div><div className="stat"><span>📈 vs average</span><b className={latestScore>=globalAverage?'success':'error'}>{latestScore>=globalAverage?'+':''}{(latestScore-globalAverage).toFixed(1)}</b></div><div className="stat"><span>🏅 Achievements</span><b>{achievements?.length||0}</b></div></div><AnalyticsDashboard attempts={attempts||[]} topics={topics}/><div className="section-title"><h2>Achievements</h2><a href="/leaderboard">Leaderboard →</a></div><div className="grid3">{(achievements||[]).slice(0,3).map((a:any)=><div className="card card-hover" key={a.achievement_key}><div style={{fontSize:28}}>{a.achievements?.icon||'🏅'}</div><h3>{a.achievements?.name||a.achievement_key}</h3><p className="muted">{a.achievements?.description}</p></div>)}{!achievements?.length&&<div className="card"><h3>Earn your first badge</h3><p className="muted">Complete a mock, build a streak, or solve 100 questions.</p></div>}</div><div className="section-title"><h2>Quick revision</h2><Link href="/revision">Open revision →</Link></div><div className="grid3"><div className="card card-hover"><div className="eyebrow">MISTAKES</div><h3>Review incorrect answers</h3><p className="muted">Turn errors from recent attempts into your next study set.</p></div><div className="card card-hover"><div className="eyebrow">STREAK</div><h3>Keep your activity alive</h3><p className="muted">A small daily practice session is better than a last-minute cram.</p></div><div className="card card-hover"><div className="eyebrow">WEAK TOPICS</div><h3>Target the lowest accuracy</h3><p className="muted">Use analytics to decide what to revise next.</p></div></div></main></div>
}
